### ISSUE TITLE
Template inheritance issue 

### ISSUE THREAD

**Issue by bastbnl** [clokep/django-render-block#12]
I'm using django-render-block via django-templated-email 2.2.0 on Django 1.11.7 using python 2.7 and I'm running into an issue when using this layout:

project/application/templates/templated_email/message_base.txt
project/application/templates/templated_email/eng/message-meeting-cancelled.email
project/application/templates/templated_email/eng/message-meeting-cancelled-participants.email

The idea is to render a "generic" meeting cancelled email, via the second template, and include additional detail into more specialised templates. The details are in `message-meeting-cancelled-participants.email`.

`templated_email/message_base.txt` has this:
```
...
{% block subject %}{{ site.name }}: {% block subject_content_block %}{% endblock %}{% endblock %}

{% block plain %}
{% block plain_salutation_block %}Hi,{% endblock plain_salutation_block %}
Best open this message using an app that supports formatted email ;-)

{% block plain_content %}
{% endblock plain_content %}
{% block plain_signature_block %}
Thanks for using our service,
-- {{ site.name }} Admin
{% endblock plain_signature_block %}
{% endblock plain %}
...
```

`templated_email/eng/message-meeting-cancelled.email` has some basic information concerning cancellation. The idea is that I'll update that with the detailed template, effectively making this a base template. So here's part of what's in the template:
```
{% extends 'templated_email/message_base.txt' %}
...
{% block subject_content_block %}Meeting {{ meeting.label }} was just cancelled{% endblock %}

{% block plain_salutation %}Hi {{ participant.first_name | default:'there'}},{% endblock %}

{% block plain_content %}
You have been invited to the "{{ meeting.label }}" meeting at {{ site.name }} {% if confirmed_attendance %}and you confirmed your attendance{% endif %}.

{% block plain_reason_detail %}
{% endblock %}

{% endblock %}
...
```

`templated_email/eng/message-meeting-cancelled-participants.email` contains the relevant information for cancelling that meeting:

```
{% extends 'templated_email/eng/message-meeting-cancelled.email' %}

{% block plain_reason_detail %}
The meeting was scheduled to run at {{ meeting.scheduled_at }}. Too many people were unable to attend to the meeting.
{% endblock %}

```

Here's the issue when I run the template:
```
>>> from render_block import *
>>> render_block_to_string('templated_email/eng/message-meeting-cancelled-participants.email', 'plain')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/var/www/brownpapersession/dev/env-brownpapersession/local/lib/python2.7/site-packages/render_block/base.py", line 39, in render_block_to_string
    return django_render_block(t, block_name, context)
  File "/var/www/brownpapersession/dev/env-brownpapersession/local/lib/python2.7/site-packages/render_block/django.py", line 41, in django_render_block
    parent_template, block_name, context_instance)
  File "/var/www/brownpapersession/dev/env-brownpapersession/local/lib/python2.7/site-packages/render_block/django.py", line 74, in _render_template_block
    return _render_template_block_nodelist(template.nodelist, block_name, context)
  File "/var/www/brownpapersession/dev/env-brownpapersession/local/lib/python2.7/site-packages/render_block/django.py", line 106, in _render_template_block_nodelist
    raise BlockNotFound("block with name '%s' does not exist" % block_name)
BlockNotFound: block with name 'plain' does not exist
```

It does work properly when I run `message-meeting-cancelled.email`:
```
from render_block import *
render_block_to_string('templated_email/eng/message-meeting-cancelled.email', 'plain')
```

Am I missing something?

**Comment by bastbnl** [comment]
I tried to work this out and found that the block names are present in `context.render_context[BLOCK_CONTEXT_KEY]`. That got me thinking. PR coming up

**Comment by clokep** [comment]
Interesting. I'll be curious to see what you find! 👍

**Comment by bastbnl** [comment]
Looks like I'm introducing a new issue here. I'll look into that
```
...
  File "/var/www/brownpapersession/dev/env-brownpapersession/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/www/brownpapersession/dev/env-brownpapersession/local/lib/python2.7/site-packages/django/template/base.py", line 960, in render_annotated
    e.template_debug = context.render_context.template.get_exception_info(e, self.token)
AttributeError: 'NoneType' object has no attribute 'get_exception_info'
```

**Comment by clokep** [comment]
I think that #56 might fix this, but would be curious for more real world testing!
