### ISSUE TITLE
Exceptions in templates are being hidden

### ISSUE THREAD

**Issue by yaakovLowenstein** [clokep/django-render-block#51]
I came across an issue where errors in templates are being hidden because they get swallowed by a different error (stack trace below) when in DEBUG mode which makes debugging the error very difficult.

The error below is raised when in debug mode and there is no template attached to the `context.render_context`

```
Traceback (most recent call last):
  File "/home/yaakov/dev/django-render-block/.venv/lib/python3.10/site-packages/django/test/utils.py", line 443, in inner
    return func(*args, **kwargs)
  File "/home/yaakov/dev/django-render-block/.venv/lib/python3.10/site-packages/django/test/utils.py", line 443, in inner
    return func(*args, **kwargs)
  File "/home/yaakov/dev/django-render-block/tests/tests.py", line 103, in test_block_from_grandparent_when_parent_supers_the_block
    result = render_block_to_string("test8.html", "block6")
  File "/home/yaakov/dev/django-render-block/render_block/base.py", line 39, in render_block_to_string
    return django_render_block(t, block_name, context, request)
  File "/home/yaakov/dev/django-render-block/render_block/django.py", line 41, in django_render_block
    return _render_template_block(template, block_name, context_instance)
  File "/home/yaakov/dev/django-render-block/render_block/django.py", line 87, in _render_template_block
    return _render_template_block_nodelist(template.nodelist, block_name, context)
  File "/home/yaakov/dev/django-render-block/render_block/django.py", line 102, in _render_template_block_nodelist
    return node.render(context)
  File "/home/yaakov/dev/django-render-block/.venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/yaakov/dev/django-render-block/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/yaakov/dev/django-render-block/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/yaakov/dev/django-render-block/.venv/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    and context.render_context.template.origin == e._culprit_node.origin
AttributeError: 'NoneType' object has no attribute 'origin'
```

**Comment by yaakovLowenstein** [comment]
Created a PR to fix it https://github.com/clokep/django-render-block/pull/52/files
